spring.application.name=securitydemo
spring.app.jwtSecret=MySecret150378696abcge78fgh234444yuuoikjtr655r7698uykjghgderwtyfkjbkjhiputrstrfdhg
spring.app.jwtExpirationMs=800000000

logging.level.org.springframework=DEBUG;
logging.level.org.springframework.security=DEBUG;
logging.level.com.ivoyant.securitydemo=DEBUG;

